# 1. Create a 3x3x3 array with random values 

In [5]:
import numpy as np
array=np.random.random((3,3,3))
print(array)

[[[0.64523404 0.01226323 0.20127309]
  [0.49979488 0.1002295  0.93617129]
  [0.65672485 0.65067367 0.49872403]]

 [[0.66303535 0.03540172 0.61585464]
  [0.23781783 0.56031637 0.74854335]
  [0.68638108 0.51486625 0.49612394]]

 [[0.82953782 0.39219863 0.61469266]
  [0.43153747 0.85621533 0.56568386]
  [0.25621442 0.90224479 0.95496546]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
import numpy as np
y = np.diag([1,2,3,4],k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [29]:
x = np.ones((3,3))
x = np.zeros((8,8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [32]:
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.39155273 0.57690438 0.21637623]
 [0.45854071 0.56500829 0.53091966]
 [0.89128441 0.97325707 0.16162256]]
After normalization:
[[0.28329275 0.51166112 0.067461  ]
 [0.36582741 0.49700416 0.4550042 ]
 [0.89900299 1.         0.        ]]


In [34]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.39004095 -1.13404435  1.51460045 -0.07584933 -0.94595178]
 [-1.35732003  0.36601331 -0.22579244  0.38860379  1.4294539 ]
 [-0.11478047  0.38945695  1.12259177  0.0281551  -0.09130133]
 [-0.77904579 -0.41771879 -1.55393928  1.35952621  0.12353387]
 [-1.56915832  1.513165    0.57301693 -1.6458235  -0.28743282]]


# 5.  How to find common values between two arrays?

In [58]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z2, Z2))

[0 1 3 4 5 7 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [61]:
from datetime import datetime, timedelta 

presentday = datetime.now() 
yesterday = presentday - timedelta(1) 
tomorrow = presentday + timedelta(1) 
    
# strftime() is to format date according to 
# the need by converting them to string 
print("Yesterday = ", yesterday.strftime('%d-%m-%Y')) 
print("Today = ", presentday.strftime('%d-%m-%Y')) 
print("Tomorrow = ", tomorrow.strftime('%d-%m-%Y')) 

Yesterday =  29-07-2020
Today =  30-07-2020
Tomorrow =  31-07-2020


In [62]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-07-29
2020-07-30
2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [67]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

compare = A == B
equal_arrays = comparison.all()
print(equal_arrays)

False
False
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [70]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.62346854 0.79286859 0.         0.01958482 0.82684399 0.53242841
 0.19876604 0.61426125 0.49500073 0.5094294 ]


# 9. How to print all the values of an array?

In [71]:
import numpy as np
np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [73]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [89]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[ 0.25533394  0.2514639  -0.12717454  0.32064929 -0.24401758  0.0430976
  -0.36569164  0.40497849 -0.49659925 -0.04204021]
 [ 0.13296999 -0.44919076 -0.18178268 -0.165795   -0.14834133  0.08262876
   0.30055961  0.14850998 -0.18766913  0.46811057]
 [ 0.04205243 -0.33766966 -0.08400676  0.52724835  0.2440623  -0.03994756
   0.23894041 -0.05879849 -0.28468123 -0.24719978]
 [-0.24758921 -0.4185526   0.48958418  0.2232906   0.41199316  0.15215142
  -0.47871102  0.43017397 -0.12727113 -0.43506937]
 [ 0.32770156 -0.01542989  0.08970786 -0.44203588  0.04532346 -0.28615965
   0.0984965  -0.04963205  0.35747081 -0.12544273]]
[[ 0.25533394  0.2514639  -0.12717454  0.32064929 -0.24401758  0.0430976
  -0.36569164  0.40497849 -0.49659925 -0.04204021]
 [ 0.13296999 -0.44919076 -0.18178268 -0.165795   -0.14834133  0.08262876
   0.30055961  0.14850998 -0.18766913  0.46811057]
 [ 0.04205243 -0.33766966 -0.08400676  0.52724835  0.2440623  -0.03994756
   0.23894041 -0.05879849 -0.28468123 -0.24719978]
 

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [91]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 4. 3. 2. 1. 3. 3. 3. 4.]


In [92]:
np.add.at(Z, I, 1)
print(Z)

[7. 5. 7. 5. 3. 1. 5. 5. 5. 7.]


In [93]:
vector=np.array([1,2,3,4,5])
add_1=lambda i:i+1
vectorized=np.vectorize(add_1)
vectorized(vector)

array([2, 3, 4, 5, 6])

# 12.How to get the diagonal of a dot product?

In [102]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.47143861 0.68270635 0.78363188 0.01181826 0.80586849]
 [0.78940052 0.49477352 0.43654406 0.28164255 0.44712443]
 [0.97919522 0.18151675 0.82317873 0.81016422 0.64713597]
 [0.26429569 0.64725146 0.38053234 0.88783319 0.85359229]
 [0.43474252 0.68512588 0.82066533 0.93710218 0.51983363]]
[[0.44785749 0.98457304 0.56839981 0.89930631 0.72575466]
 [0.75183768 0.55347725 0.77155037 0.95034049 0.62768173]
 [0.03001103 0.49056269 0.45638698 0.04977898 0.55991881]
 [0.19686297 0.70063751 0.03983053 0.17928706 0.83491134]
 [0.57152859 0.31328318 0.28403907 0.57573674 0.37850159]]
diagonal of a dot product method 1 is.... [1.21084273 1.60262648 1.2883929  1.52235601 2.18421845]
diagonal of a dot product method 2 is.... [1.21084273 1.60262648 1.2883929  1.52235601 2.18421845]


In [101]:
a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)

print(np.diag(np.dot(np.dot(a, b), a.T)))

print(np.einsum('ij,ji->i', np.dot(a, b), a.T))

print(np.einsum('ij,ij->i', np.dot(a, b), a))

[  60  672 1932 3840 6396]
[  60  672 1932 3840 6396]
[  60  672 1932 3840 6396]


# 13.How to find the most frequent value in an array?

In [113]:
 x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:") 
print(np.bincount(x).argmax())

Original array:
[7 8 5 0 8 6 2 7 9 2 4 7 1 7 8 4 9 3 9 3 5 3 7 2 1 5 7 1 8 7 8 8 7 1 3 5 3
 8 2 2]
Most frequent value in the above array:
7


# 14.How to get the n largest values of an array

In [124]:
arr=np.array([12,45,65,90,37,39])
n=2
arr.sort()
print(arr[-n:])

[65 90]


In [125]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [126]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [128]:
x = np.array([(1.0, 4.0,), (2.0, -1.0)], dtype=[('f0', '<f8'), ('f1', '<f8')])
print(x)

[(1.,  4.) (2., -1.)]


In [133]:
np.array(x.tolist())

array([[ 1.,  4.],
       [ 2., -1.]])